kino/urls.py
"""This is the URL module.
"""

__all__ = ['FilmForm', ]
__version__ = '0.1'
__author__ = 'Artem Yurchak'

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from kino.views.admin_panel.banners import *
from kino.views.admin_panel.cinema import *
from kino.views.admin_panel.film import *
from kino.views.admin_panel.home import *
from kino.views.admin_panel.mailing import *
from kino.views.admin_panel.news import *
from kino.views.admin_panel.pages import *
from kino.views.admin_panel.shares import *
from kino.views.admin_panel.statistics import *
from kino.views.admin_panel.user import *
from kino.views.admin_panel.schedule import *
from kino.views.admin_panel.ads import *
from kino.views.site.cinema import *
from kino.views.site.film import *
from kino.views.site.home import *
from kino.views.site.news import *
from kino.views.site.schedule import *
from kino.views.site.shares import *
from kino.views.site.children_room import *
from kino.views.site.cafe_bar import *
from kino.views.site.vip_hall import *
from kino.views.site.advertising import *
from kino.views.site.mobile_app import *
from kino.views.site.contacts import *


urlpatterns = [
    # Site KinoCMS.
    path('',
         home_page_view,
         name='home'),
    path('schedule/',
         schedule_page_view,
         name='schedule'),
    path('poster/',
         poster_view,
         name='poster'),
    path('premiere/',
         premiere_view,
         name='premiere'),
    path('film/<int:film_id>',
         film_detail_view,
         name='film_detail'),
    path('cinemas/',
         ciname_view,
         name='cinemas'),
    path('cinema/<int:cinema_id>',
         cinema_detail_view,
         name='cinema_detail'),
    path('cinema/<int:cinema_id>/hall/<int:cinemahall_id>',
         cinemahall_detail_view,
         name='cinemahall_detail'),
    path('shares/',
         shares_view,
         name='shares'),
    path('shares/<int:shares_id>',
         shares_detail_view,
         name='shares_detail'),
    path('news/',
         news_view,
         name='news'),
    path('news/<int:news_id>',
         news_detail_view,
         name='news_detail'),
    path('children-room/',
         children_room_page_view,
         name='children_room'),
    path('cafe-bar/',
         cafe_bar_page_view,
         name='cafe_bar'),
    path('vip-hall/',
         vip_hall_page_view,
         name='vip_hall'),
    path('advertising/',
         advertising_page_view,
         name='advertising'),
    path('contacts/',
         contacts_page_view,
         name='contacts'),
    path('mobile_app/',
         mobile_app_page_view,
         name='mobile_app'),
    path('about/',
         children_room_page_view,
         name='about'),

    # Admin schedule.
    path('admin/schedule/',
         admin_schedule_view,
         name='admin_schedule'),
    path('admin/schedule/add/',
         admin_schedule_create_view,
         name='admin_create_schedule'),
    path('admin/schedule/<int:schedule_id>/update/',
         admin_schedule_update_view,
         name='admin_update_schedule'),
    path('admin/schedule/<int:pk>/delete/',
         AdminScheduleDeleteView.as_view(),
         name='admin_delete_schedule'),

    # Admin users.
    path('admin/users/',
         adminUserListView,
         name='admin_users'),
    path('admin/users/create/',
         adminUserCreateView,
         name='admin_create_users'),
    path('admin/users/edit/<int:user_id>',
         adminUserUpdateView,
         name='admin_update_users'),
    path('admin/users/<int:user_id>/delete',
         adminUserDeleteView,
         name='admin_delete_user'),
    path('admin/users/',
         adminUserListView,
         name='admin_users'),

    # Admin sidebar.
    path('admin/',
         admin_view,
         name='admin_home'),
    path('admin/statistics/',
         adminStatisticsView,
         name='admin_statistics'),
    path('admin/banners/sliders/',
         slider_banners_update,
         name='admin_banners_sliders'),
    path('admin/banners/background/',
         back_banners_update,
         name='admin_banners_back'),
    path('admin/banners/shares/',
         shares_banners_update,
         name='admin_banners_shares'),
    path('admin/shares/',
         AdminSharesView.as_view(),
         name='admin_shares'),
    path('admin/pages/',
         admin_pages_view,
         name='admin_pages'),
    path('admin/pages/ads/',
         admin_ads_view,
         name='admin_ads'),
    path('admin/pages/home/',
         admin_home_page_view,
         name='admin_homepage'),
    path('admin/pages/contacts/',
         admin_contacts_page_view,
         name='admin_contacts_page'),
    path('admin/pages/cafe-bar/',
         admin_cafe_bar_page_view,
         name='admin_cafe-bar_page'),
    path('admin/pages/vip-hall/',
         admin_vip_hall_page_view,
         name='admin_vip-hall_page'),
    path('admin/pages/advertising/',
         admin_advertising_page_view,
         name='admin_advertsing_page'),
    path('admin/pages/children_room/',
         admin_children_room_page_view,
         name='admin_children_room_page'),
    path('admin/pages/mobile_app/',
         admin_mobile_app_page_view,
         name='admin_mobile_app_page'),

    # Mailing of users.
    path('admin/mailing/all/',
         mailing_all_users,
         name='mailing_all_users'),
    path('admin/mailing/group/',
         mailing_group_of_users,
         name='mailing_group_of_users'),

    # Admin films.
    path('admin/films/',
         AdminFilmsView.as_view(),
         name='admin_films'),
    path('admin/films/create/',
         admin_film_create_view,
         name='admin_create_film'),
    path('admin/films/<int:film_id>',
         admin_film_detail_view,
         name='admin_film_detail'),
    path('admin/films/<int:film_id>/update/',
         admin_film_update_view,
         name='admin_update_film'),
    path('admin/films/<int:pk>/delete',
         AdminFilmDeleteView.as_view(),
         name='admin_delete_film'),

    # Admin cinemas.
    path('admin/cinemas/',
         AdminCinemasView.as_view(),
         name='admin_cinemas'),
    path('admin/cinemas/create/',
         admin_cinema_create_view,
         name='admin_create_cinema'),
    path('admin/cinemas/<int:cinema_id>/',
         admin_cinema_detail_view,
         name='admin_cinema_detail'),
    path('admin/cinemas/<int:cinema_id>/update/',
         admin_cinema_update_view,
         name='admin_update_cinema'),
    path('admin/cinemas/<int:pk>/delete/',
         AdminCinemaDeleteView.as_view(),
         name='admin_delete_cinema'),

    # Admin cinema hall.
    path('admin/cinemas/<int:cinema_id>/cinemahall/create/',
         admin_cinemahall_create_view,
         name='admin_add_cinemahall'),
    path('admin/cinemas/<int:cinema_id>/cinemahall/<int:cinemahall_id>/',
         admin_cinemahall_detail_view,
         name='admin_cinemahall_detail'),
    path('admin/cinemas/<int:cinema_id>/cinemahall/<int:cinemahall_id>/update/',
         admin_cinemahall_update_view,
         name='admin_update_cinemahall'),
    path('admin/cinemas/<int:cinema_id>/cinemahall/<int:cinemahall_id>/delete/',
         admin_cinemahall_delete_view,
         name='admin_delete_cinemahall'),

#     # Admin cinema hall type.
#     path('admin/cinemas/<int:cinema_id>/cinemahall/type/add/',
#          admin_cinemahall_type_add,
#          name='admin_cinemahall_type_add'),


#     # Admin cinema hall type.
#     path('admin/cinemas/<int:cinema_id>/cinemahall/type/add/',
#          admin_cinemahall_type_add,
#          name='admin_cinemahall_type_add'),


    # Admin news.
    path('admin/news/',
         AdminNewsView.as_view(),
         name='admin_news'),
    path('admin/news/create/',
         admin_news_create_view,
         name='admin_create_news'),
    path('admin/news/<int:news_id>',
         admin_news_detail_view,
         name='admin_news_detail'),
    path('admin/news/<int:news_id>/update/',
         admin_news_update_view,
         name='admin_update_news'),
    path('admin/news/<int:pk>/delete',
         AdminNewsDeleteView.as_view(),
         name='admin_delete_news'),

    # Admin shares.
    path('admin/shares/',
         AdminSharesView.as_view(),
         name='admin_shares'),
    path('admin/shares/create/',
         admin_shares_create_view,
         name='admin_create_shares'),
    path('admin/shares/<int:shares_id>',
         admin_shares_detail_view,
         name='admin_shares_detail'),
    path('admin/shares/<int:shares_id>/update/',
         admin_shares_update_view,
         name='admin_update_shares'),
    path('admin/shares/<int:pk>/delete',
         AdminSharesDeleteView.as_view(),
         name='admin_delete_shares'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kinocms/urls.py
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('djadmin/', admin.site.urls),
                  path('', include('kino.urls')),
                  path('profile/', include('django.contrib.auth.urls')),
                  path('profile/', include('register.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kino/models/ads.py
"""This is the ads module.

This module has ads image and url view.
"""

__version__ = '0.1'
__author__ = 'Artem Yurchak'

from django.db import models

class ADS(models.Model):
    """Ads model has fields:
    image, url.
    """
    image = models.FileField(upload_to='images/ads')
    url = models.URLField()
    

kino/models/cinema.py
import datetime

from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField, HStoreField


def upload_cinema_preview(instance, filename):
    return f"cinema/{instance.name}/preview/{filename}"


def upload_cinema_logo(instance, filename):
    return f"cinema/{instance.name}/logo_of_cinema/{filename}"


def upload_cinemahall_preview(instance, filename):
    return f"cinema/{instance.cinema.name}/halls/{instance.name}/preview/{filename}"


class Cinema(models.Model):
    name = models.CharField(
        max_length=50,
        default=''
    )
    description = models.TextField(
        max_length=1000,
        blank=True
    )
    conditions = models.TextField(
        max_length=1000,
        blank=True
    )
    logo = models.ImageField(
        upload_to=upload_cinema_logo,
        blank=True
    )
    preview = models.ImageField(
        upload_to=upload_cinema_preview,
        blank=True
    )
    seo_title = models.CharField(
        max_length=50,
        blank=True
    )
    seo_keywords = models.CharField(
        max_length=100,
        blank=True
    )
    seo_description = models.TextField(
        max_length=100,
        blank=True
    )

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("admin_cinemas")


class CinemaHall(models.Model):
    cinema = models.ForeignKey(
        Cinema,
        default='',
        on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=50,
        default=''
    )
    created_date = models.DateField(
        default=datetime.datetime.now
    )
    description = models.TextField(
        max_length=1000,
        blank=True
    )
    scheme = models.ImageField(
        upload_to='images/scheme'
    )
    preview = models.ImageField(
        upload_to=upload_cinemahall_preview
    )
    seo_title = models.CharField(
        max_length=50,
        blank=True
    )
    seo_keywords = models.CharField(
        max_length=100,
        blank=True
    )
    seo_description = models.CharField(
        max_length=100,
        blank=True
    )

    def __str__(self):
        return f'{self.name}'


# class HallType(models.Model):
#     name = models.CharField(
#         max_length=200,
#         null=False,
#         editable=True
#     )
#     seats = ArrayField(
#         HStoreField()
#     )

kino/models/film.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import mark_safe

from utils import current_year


def upload_film_preview(instance, filename):
    return f"films/{instance.name}/preview/{filename}"


YEAR_CHOICES = [(r, r) for r in range(1900, current_year() + 1)]

GENRES = (
    (1, 'Sci-Fi'),
    (2, 'Detective'),
    (3, 'Horror'),
    (4, 'Anime'),
    (5, 'Thriller'),
)


class Film(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Name',
        default='',
    )
    year = models.IntegerField(
        verbose_name='Year',
        choices=YEAR_CHOICES,
        default=timezone.now().year
    )
    country = models.CharField(
        max_length=100,
        default=''
    )
    director = models.CharField(
        max_length=65,
        default=''
    )
    producer = models.CharField(
        max_length=65,
        default=''
    )
    music = models.CharField(
        verbose_name='Music By:',
        max_length=65,
        default='')
    scenarist = models.CharField(
        verbose_name='Written By:',
        max_length=65,
        default=''
    )
    genre = models.CharField(
        max_length=50,
        null=True
    )
    description = models.TextField(
        max_length=1000,
        default=''
    )
    video = models.URLField(
        blank=True
    )
    premiere = models.DateField(
        editable=True,
        default=timezone.now
    )
    preview = models.FileField(
        upload_to=upload_film_preview
    )
    two_dimensions = models.BooleanField(
        default=False,
        null=True
    )
    three_dimensions = models.BooleanField(
        default=False,
        null=True
    )
    imax = models.BooleanField(
        default=False,
        null=True
    )
    duration = models.TimeField(
        editable=True,
        null=True,
        verbose_name='Duration of film:'
        )
    seo_title = models.CharField(
        max_length=50,
        blank=True
    )
    seo_keywords = models.CharField(
        max_length=100,
        blank=True
    )
    seo_description = models.CharField(
        max_length=100,
        blank=True
    )

    def __str__(self):
        return f"{self.name}"

    def image_tag(self):
        return mark_safe(
            '<img src="/directory/%s" width="150" height="150" />'
            % (self.preview))

    def get_absolute_url(self):
        return reverse("admin_films")

    def get_premiere(self):
        if self.premiere >= timezone.now().date():
            return True
        else:
            return False

    def get_current(self):
        if self.premiere < timezone.now().date():
            return True
        else:
            return False

kino/models/news.py
from django.utils import timezone
from django.db import models
from django.urls import reverse


def upload_news_preview(instance, filename):
    return f"news/{instance.name}/preview/{filename}"


class News(models.Model):
    """Class News which using for News pageW"""

    STATUS_CHOICES = [
        ('ON', 'On'),
        ('OFF', 'Off'),
    ]

    name = models.CharField(
        max_length=50,
        default=''
    )
    pub_date = models.DateField(
        editable=True,
        default=timezone.now
    )
    description = models.TextField(
        max_length=1000
    )
    status = models.CharField(
        max_length=10,
        default=STATUS_CHOICES[1],
        choices=STATUS_CHOICES
    )
    preview = models.ImageField(
        upload_to=upload_news_preview,
        null=True
    )
    video = models.URLField(
        blank=True
    )
    seo_title = models.CharField(
        max_length=50,
        blank=True
    )
    seo_keywords = models.CharField(
        max_length=100,
        blank=True
    )
    seo_description = models.CharField(
        max_length=100,
        blank=True
    )

    def __str__(self):
        """Func that returning name of curent news"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Func returning url needed 
        after succeed update instance of the news
        """
        return reverse("admin_news")

    def get_status(self):
        if self.status == 'ON':
            return True
        else:
            return False

kino/models/schedule.py
from django.db import models
from django.utils import timezone

from kino.models.film import Film
from kino.models.cinema import CinemaHall


class Schedule(models.Model):

    film = models.ForeignKey(
        Film,
        null=True,
        on_delete=models.CASCADE
    )

    cinemahall = models.ForeignKey(
        CinemaHall,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Hall:'
    )
    cost = models.CharField(
        max_length=25,
        null=True,
        default=0,
        verbose_name='Minimum cost:'
    )
    two_dimensions = models.BooleanField(
        default=False,
        null=True
    )
    three_dimensions = models.BooleanField(
        default=False,
        null=True
    )
    imax = models.BooleanField(
        default=False,
        null=True
    )
    date = models.DateField(
        editable=True,
        null=True,
        default=timezone.now
    )
    time = models.TimeField(
        editable=True,
        null=True,
        default=timezone.now,
        verbose_name='Start time:'
    )

    def __str__(self):
        return str(self.date)

    def get_status(self):
        if self.date >= timezone.now().date():
            return True
        else:
            return False

kino/templates/kino/cinema_detail.html
{% extends 'kino/base.html' %}
{% load static %}

<head>
    <meta name="description" property="og:description" content="{{cinema.seo_description}}">
    <meta name="keywords" content="{{cinema.seo_keywords}}">    
</head>

{% block title %}
    <title>Cinema {{cinema.seo_title|truncatechars:20}}</title>
{% endblock title %}

{% block content %}
{% if cinema.preview %}
<img class="img-fluid" src="{{ cinema.preview.url }}" alt="{{ cinema.preview }}" width="100%" style="max-height:100vh !important;">
{% endif %}
<br><br>

<div class="row bg-light" style="min-height: 70vh; padding-left:2%" >
    <div class="col-md-3">
        <div class="text-center">
        <br>
            <a href="{{ads.url}}"><img src="{{ads.image.url}}" class="img-fluid" alt="{{ads.image}}" width="100%" style="max-height:50vh;"></a>
        </div>
        <br>
        {% if cinemahalls %}
        <div class="box">
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                    <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column descending" aria-sort="ascending">Halls</th>
                    </thead>
                    {% for cinemahall in page_obj %}
                        <tbody>
                            <tr role="row" class="odd">
                                <td class="sorting_1"><a class="text-decoration-none" href="{% url 'cinemahall_detail' cinema.id cinemahall.id%}">{{cinemahall.name|truncatechars:20}}</a></td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
                {% else %}
                    <h3 style="color:red;">Halls will be soon! :)</h3>
                {% endif %}
            </div>
        </div>
        <hr>
        <div>
            <h5>Watch today:</h5>
            {% if schedule_list %}
                <div class="row">
                    {% regroup schedule_list by date as day_list %}
                    {% for day in day_list%}                                 
                        <h6>{{day.grouper}}</h6>
                        <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                            <thead class="thead-dark">
                                <tr role="row">
                                    <th class="sorting_asc text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Start time</th>
                                    <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Film</th>
                                    <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Hall</th>
                                    <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Minimum cost</th>
                                    <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Book a ticket</th>
                                </tr>
                            </thead>
                            <tbody> 
                                {% for item in day.list %}
                                    <tr role="row" class="odd">
                                        <td class="text-center" width="10%">{{item.time}}</td>
                                        <td class="text-center" width="40%">{{item.film|truncatechars:50}}</td>
                                        <td class="text-center" width="10%">{{item.cinemahall|truncatechars:40}}</td>
                                        <td class="text-center" width="10%">{{item.cost}}</td>
                                        <td class="text-center" width="10%"><a href="#"><i class="fa fa-ticket"></i></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endfor %}
                </div>
            {% else %}
                <blockquote class="text-center">
                    <p class="blockquote text-center">There is no schedule yet.. </p> 
                </blockquote>
            {% endif %}
        </div>
        <div>
            <a class="btn btn-success" href="{% url 'schedule' %}">All sessions</a>
        </div>
    </div>

    <div class="col-md-8">
        <br>
        <div class="row">
            <div class="col-md-3">
                <h3 class="box-title" style="word-break: break-all;">«{{ cinema.name }}»</h3>
            </div> 
            <div class="col-md-3">
                <img src="{{ cinema.logo.url }}" alt="{{ cinema.logo }}" style="max-width: 100px; height:auto;"></br>
            </div>
            <div class="col-md-6">
                <a class="btn btn-success" href="{% url 'schedule' %}">Schedule</a>
                <h3 class="box-title">Type of cinema(viphall,3d, dolby atmos, D-box)</h3>
            </div>
        </div>
        <hr>
        <div style="word-break: break-all;">
            <h3 class="text-center" >Description</h3>
            {{ cinema.description}}
        </div>
        <br>
        <div style="word-break: break-all;">
            <h3 class="text-center" >Conditions</h3>
            {{ cinema.conditions}}
        </div>
        <br>
        <h3 class="text-center">Gallery</h3>
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"> 
            <ol class="carousel-indicators">
                {% comment %} DYNAMIC CAROUSEL BOTTOM INDICATOR {% endcomment %}
                {% for image in gallery %}
                    {% if forloop.counter0|divisibleby:"1" %}
                        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{forloop}}"{% if forloop.first %} class="active" {% endif %}></li>
                    {% endif %}
                {% endfor %}
            </ol>
            
            <div class="carousel-inner">
                {% for image in gallery %}
                    {% if forloop.counter0|divisibleby:"1" %}
                        <div class="carousel-item {% if forloop.first %} active {% endif %}"> 
                            <div class="row">{% endif %}
                                <a href="{{ image.url }}#"><img class="d-block w-100" src="{{image.image.url}}" alt="{{image.image1}}" style="height: 80vh !important;"></a>
                                {% if forloop.counter0|divisibleby:"1" %}
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{image.text}}</h5>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </a>

            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </a>
        </div>
        <br>
    </div>

    <div class="col-md-1"></div>  

</div>
{% endblock content %}

kino/templates/kino/cinemas.html
{% extends 'kino/base.html' %}
{% load static %}

<head>
    <meta name="description" property="og:description" content="{{cinema.seo_description}}">
    <meta name="keywords" content="{{cinema.seo_keywords}}">    
</head>

{% block title %}
    <title>Cinemas</title>
{% endblock title %}

{% block content %}
<div class="row" style="min-height: 70vh;">
    <div class="col-md-1"></div>    
    <div class="col-md-9 bg-light">
        <div class="container">
            <h1 class="text-center">Cinemas</h1>
            {% if cinema_list %}
            <div class="row">
                {% for cinema in cinema_list %}
                    <div class="col-md-6">
                        <div class="card mb-6 shadow-sm">
                            <a class="text-decoration-none" href="{% url 'cinema_detail' cinema.id%}"><img class="card-img-top" src="{{ cinema.preview.url }}" alt="{{ cinema.preview }}" style="height: 50vh; width: 100%%; display: block;">
                            <div class="card-body">
                                <h4 class="card-text text-center ">{{ cinema.name }}</h4>
                                <div class="d-flex justify-content-between align-items-center">
                                </div>
                            </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <blockquote class="text-center">
                    <p class="blockquote text-center">Sooo empty.. 🙄</p> 
                </blockquote>
            {% endif %}
        </div>
    </div> 
    <div class="col-md-2">
        <div class="text-center">
            <a href="{{ads.url}}"><img src="{{ads.image.url}}" class="img-fluid" alt="{{ads.image}}" width="100%" style="max-height:50vh;"></a>
        </div> 
    </div>
</div>
{% endblock  %}

kino/templates/kino/news.html
{% extends 'kino/base.html' %}
{% load static %}

{% block title %}
    <title>News</title>
{% endblock title %}

{% block content %}

<div class="row" style="min-height: 70vh;">
    <div class="col-md-1"></div>   
    <div class="col-md-9 bg-light">
        <div class="album py-3">
            <div class="container">
                <h1 class="text-center">News</h1>
                {% if news_list %}
                <div class="row">
                    {% for news in news_list %}
                        {% with news.get_status as s %}
                            {% if news.get_status %}
                                <div class="col-md-3">
                                    <div class="card mb-3 shadow-sm">
                                        <a class="text-decoration-none" href="{% url 'news_detail' news.id%}"><img class="card-img-top" src="{{ news.preview.url }}" alt="{{ news.preview }}" style="height: 250px; width: 100%%; display: block;">
                                        <div class="card-body">
                                            <h4 class="card-text text-center">{{ news.name }}</h4></a>
                                            <p class="card-text">Published: {{ news.pub_date }}</p>
                                            <div class="d-flex justify-content-between align-items-center" style="word-break: break-all;">
                                                {{news.description|truncatechars:50}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %} 
                        {% endwith %}
                    {% endfor %}
                </div>
                {% else %}
                    <blockquote class="text-center">
                        <p class="blockquote text-center">Sooo empty.. 🙄</p> 
                    </blockquote>
                {% endif %}
            </div> 
        </div>
    </div>
    <div class="col-md-2">
        <div class="text-center">
            <a href="{{ads.url}}"><img src="{{ads.image.url}}" class="img-fluid" alt="{{ads.image}}" width="100%" style="max-height:50vh;"></a>
        </div> 
    </div>
</div>
{% endblock  %}